[sources.otel_logs]
type = "vector"
address = "0.0.0.0:8686"

[sinks.clickhouse]
type = "clickhouse"
inputs = ["otel_logs"]
database = "default"
endpoint = "http://clickhouse:8123"
table = "otel_logs"
auth.user = "admin"
auth.password = "admin123"
compression = "none"
schema.fields.timestamp = "DateTime"
schema.fields.appname = "String"
schema.fields.facility = "String"
schema.fields.hostname = "String"
schema.fields.message = "String"
schema.fields.msgid = "String"
schema.fields.procid = "Int32"
schema.fields.severity = "String"
schema.fields.version = "Int32"