receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  otlp/clickhouse:
    endpoint: "clickhouse:9000" # ClickHouse address
    protocol: grpc
    tls:
      insecure: true
  otlp/jaeger:
    endpoint: "jaeger:4317" # Jaeger address
    tls:
      insecure: true
  prometheusremotewrite:
    endpoint: "http://prometheus:9090/api/v1/write"
    

#Defines the data flow for traces and metrics.
service:
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ otlp/jaeger, otlp/clickhouse ]
    metrics:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ prometheusremotewrite, otlp/clickhouse ]