receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  # Filter HTTP spans to server for `GET /health` requests because of spam.
  # See documentation for more details:
  # https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/filterprocessor
  filter/exclude-health-api-traces:
    error_mode: ignore
    traces:
      span:
        - 'attributes["http.route"] == "/health"'

  # Filter logs for `GET /health` requests logs because of spam.
  # Log line body to filter example: `Health check API invoked!`
  # See documentation for more details:
  # https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/filterprocessor
  filter/exclude-health-api-logs:
    logs:
      exclude:
        match_type: regexp
        bodies:
          - '.*Health check API invoked!.*'
  
  # Add environment attribute to all telemetry signals.
  # See documentation for more details:
  # https://opentelemetry.io/docs/collector/transforming-telemetry/#adding-or-deleting-attributes
  attributes/add-environment:
    actions:
      - key: environment
        value: development
        action: insert
  
  batch:

exporters:
  otlphttp/clickhouse:
    endpoint: http://clickhouse:8123
  
  # Data sources: traces
  otlphttp/jaeger:
    endpoint: http://jaeger:4318

  otlphttp/grafana-agent:
    endpoint: http://grafana-agent:4318

  # Data sources: metrics
  prometheus:
    endpoint: 0.0.0.0:9090
    #    namespace: products_service
  
  debug:

service:
  pipelines:
    traces:
      receivers:
        - otlp
      processors:
        - filter/exclude-health-api-traces
        - attributes/add-environment
        - batch
      exporters:
        - otlphttp/clickhouse
        - otlphttp/jaeger
        - otlphttp/grafana-agent
    
    metrics:
      receivers:
        - otlp
      processors:
        - attributes/add-environment
      exporters:
        - prometheus
        - otlphttp/grafana-agent
    
    logs:
      receivers:
        - otlp
      processors:
        - filter/exclude-health-api-logs
        - attributes/add-environment
        - batch
      exporters:
        - otlphttp/grafana-agent
        - debug 