global:
  scrape_interval: 5s
scrape_configs:
  - job_name: docker
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: [ "host.docker.internal:9323" ]
        
  - job_name: 'dotnet-services'
    static_configs:
      - targets: ['service_a:5001', 'service_b:5002']
  ###########
  - job_name: 'otel-collector'
    static_configs:
#      - targets: [ 'otel-collector:4318' ]
      - targets: [ 'otel-collector:4318' ]
  - job_name: 'vector'
    static_configs:
      - targets: [ 'vector:8686' ]