global:
  scrape_interval: 5s
scrape_configs:
  - job_name: docker
    static_configs: ## UP
      - targets: [ "host.docker.internal:9323" ]
        
  - job_name: 'dotnet-services' ## UP
    static_configs:
      - targets: ['service_a:8080', 'service_b:8080']
        
  ###########
  - job_name: 'otel-collector'
    static_configs:
      - targets: [ 'otel-collector:4318' ]
        
  - job_name: 'vector'
    static_configs:
      - targets: [ 'vector:8686' ]
        
  - job_name: 'jaeger'
    static_configs:
      - targets: [ 'jaeger:4318' ]